### ISSUE TITLE
Not changing microphone to Default Recording Device

### ISSUE THREAD

**Issue by Solanar** [AlvaroRojas/SkypeAudio#2]
This is a great product! It's been working great for switching between my speakers and headset. I recently set up a macro to switch between my headset mic and my condenser mic but Skype isn't changing its microphone when I change the Default Recording Device.

**Comment by AlvaroRojas** [comment]
Does the microphone show up in the skype dropdown?
Could you provide some screenshots of windows recording devices and skype dropdown?

**Comment by Solanar** [comment]
Window's Recording Devices: http://imgur.com/1fyJaos

Skype Microphone dropdown: http://imgur.com/JEk2IHC

I see the speakers changing in both Skype Speakers and Windows Playback Devices. I see the microphone changing in Windows Recording Devices but not in Skype Microphones.

edit: I manually set the Skype Microphone in that pic.

**Comment by AlvaroRojas** [comment]
Does it change if you set the condenser microphone as the default audio device and also in Skype settings and then only change the default audio device to the standard microphone?

**Comment by Solanar** [comment]
It's not responding to any changes in Default Recording Devices.

**Comment by Solanar** [comment]
I'm on Windows 10 with Skype up to date. I've got a headset Microphone and a Condenser Microphone, I had to rename the Condenser Microphone from Microphone to Condenser Microphone in Recording Devices so that the names wouldn't clash.

**Comment by AlvaroRojas** [comment]
I will try to replicate the issue to develop a fix.

**Comment by AlvaroRojas** [comment]
I can't replicate the issue, it's working fine in my system, I even named my two mics like yours and they change just fine, are you running the .exe as an admin?

I updated the NAudio version just so you can test if it fixes the problem for you.
[SkypeAudio.zip](https://github.com/AlvaroRojas/SkypeAudio/files/706789/SkypeAudio.zip)

**Comment by Solanar** [comment]
It works now! Awesome. I used the new version you provided. Thanks!

**Comment by AlvaroRojas** [comment]
Thank you for your time, I will deploy a new release on github with the updated files provided on this thread soon.
